### ISSUE TITLE
Meeting Summary 1 - Comments

### ISSUE THREAD

**Issue by RoeeBenhouse** [amitrub/Trading-System#1]
_**סיכום פגישה 1 – הערות מנחה**_

**שימוש ב-GitHub:**
•	Issues – מערכת תקשורת בין חברי צוות הפיתוח ובין משתמשי המערכת.   **Done**
•	Branches – לכל חבר צוות יש branch. בנוסף לזה יש שני branches: main, develop – ככה שבmain תמיד גרסה עובדת, ובdevelop  עושים את הmerge של כל הbranches  במהלך הפיתוח. - **Done**
•	להשתמש בpull request  לטובת השימוש בbranches. - **Done**
•	Wiki – להוסיף קובץ Instruction למשתמש עבור המערכת. - **Done**

**תרשים מחלקות לבן:**
•	להוריד את המחלקות Role, Guest ו- Subscriber ולהחליף אותם בקשרים עם ה- Trading System.
•	חסר permission לקשר של owner.
•	לחבר בין ה- permission של owner לבין ה- permission של manager – מחלקה או קשר שיחבר ביניהם.
•	חייב לפחות admin אחד במערכת – להוסיף את זה בקשר admin של user.
•	היסטוריית הרכישה של user – לחשוב איך כדאי לממש את זה: קשור גם ל- user וגם ל- store
•	להוסיף מחלקה שהיא Shopping cart שם תתבצע רכישת המוצרים, והיא תהיה מקושרת ל- user ול- External services.
בנוסף, היא תהיה מקושרת גם ל- store וה- Shopping bag יהיה ה- association ביניהם.
•	להוריד את הקשר בין ה- Trading System ל- External services.

**דיאגרמת ארכיטקטורה:**
•	לשנות את הקשרים והחלקות בהתאם למה ששינינו בתרשים מחלקות לבן
•	להוסיף את המחלקה Shopping cart ואת הקשר שלה עם External services.
•	להוסיף תמיכה האימות סיסמא ושם משתמש, כלומר – בדיקת תקינות. להוסיף מחלקה שתהיה אחראית על זה?

**מילון מונחים:**
•	להוסיף הגדרה ל- user.
•	הבעייתיות בקונה אורח – מה שיש בתוך הסוגריים לא מוגדר.

**תוכן עניינים:  להוסיף**

**תרחישי שימוש:**
_•	תרחיש רכישת מוצרים:_ 
o	במקום המילה 'רכש' להחליף ל- 'בחר'
o	להוריד את המדינויות מתנאי הקדם
o	פרמטרים: במקום פרטי כרטיס אשראי לרשום – פרטי תשלום
o	תהליך: לפצל לתתי תרחישים – הכוונה היא ליצור תרחיש אחד מרכזי שממנו נגזרים עוד כמה תרחישים (שהם חלק ממנו)
o	להוסיף בדיקה האם המוצר במלאי
o	לטפל בהיסטוריית רכישה של מנוי
o	עבור קונה אורח: יש צורף להוסיף בפרמטרים גם הכנסה של פרטי הלקוח: שם, כתובת, טלפון וכו'. לציין שאצל המנוי אין צורך בהכנסת הפרטים האלו מכיוון שהוא רשום למערכת ופרטיו ידועים.
o	מדיניות רכישה ומדיניות הנחה – להפריד ביניהם. המערכת בודקת כל אחד מהם בנפרד.

**Comment by reutlevy30** [comment]
> _**סיכום פגישה 1 – הערות מנחה**_
> 
> **שימוש ב-GitHub:**
> • Issues – מערכת תקשורת בין חברי צוות הפיתוח ובין משתמשי המערכת. **Done**
> • Branches – לכל חבר צוות יש branch. בנוסף לזה יש שני branches: main, develop – ככה שבmain תמיד גרסה עובדת, ובdevelop עושים את הmerge של כל הbranches במהלך הפיתוח. - **Done**
> • להשתמש בpull request לטובת השימוש בbranches. - **Done**
> • Wiki – להוסיף קובץ Instruction למשתמש עבור המערכת. - **Done**
> 
> **תרשים מחלקות לבן:**
> • להוריד את המחלקות Role, Guest ו- Subscriber ולהחליף אותם בקשרים עם ה- Trading System.
> • חסר permission לקשר של owner.
> • לחבר בין ה- permission של owner לבין ה- permission של manager – מחלקה או קשר שיחבר ביניהם.
> • חייב לפחות admin אחד במערכת – להוסיף את זה בקשר admin של user.
> • היסטוריית הרכישה של user – לחשוב איך כדאי לממש את זה: קשור גם ל- user וגם ל- store
> • להוסיף מחלקה שהיא Shopping cart שם תתבצע רכישת המוצרים, והיא תהיה מקושרת ל- user ול- External services.
> בנוסף, היא תהיה מקושרת גם ל- store וה- Shopping bag יהיה ה- association ביניהם.
> • להוריד את הקשר בין ה- Trading System ל- External services.
> 
> **דיאגרמת ארכיטקטורה:**
> • לשנות את הקשרים והחלקות בהתאם למה ששינינו בתרשים מחלקות לבן
> • להוסיף את המחלקה Shopping cart ואת הקשר שלה עם External services.
> • להוסיף תמיכה האימות סיסמא ושם משתמש, כלומר – בדיקת תקינות. להוסיף מחלקה שתהיה אחראית על זה?
> 
> **מילון מונחים:**
> • להוסיף הגדרה ל- user. -**Done**
> • הבעייתיות בקונה אורח – מה שיש בתוך הסוגריים לא מוגדר. -**Done**
> 
> **תוכן עניינים: להוסיף** -**Done**
> 
> **תרחישי שימוש:**
> _• תרחיש רכישת מוצרים:_
> o במקום המילה 'רכש' להחליף ל- 'בחר'
> o להוריד את המדינויות מתנאי הקדם
> o פרמטרים: במקום פרטי כרטיס אשראי לרשום – פרטי תשלום
> o תהליך: לפצל לתתי תרחישים – הכוונה היא ליצור תרחיש אחד מרכזי שממנו נגזרים עוד כמה תרחישים (שהם חלק ממנו)
> o להוסיף בדיקה האם המוצר במלאי
> o לטפל בהיסטוריית רכישה של מנוי
> o עבור קונה אורח: יש צורף להוסיף בפרמטרים גם הכנסה של פרטי הלקוח: שם, כתובת, טלפון וכו'. לציין שאצל המנוי אין צורך בהכנסת הפרטים האלו מכיוון שהוא רשום למערכת ופרטיו ידועים.
> o מדיניות רכישה ומדיניות הנחה – להפריד ביניהם. המערכת בודקת כל אחד מהם בנפרד.

**Comment by RoeeBenhouse** [comment]
_**סיכום פגישה 1 – הערות מנחה**_

**שימוש ב-GitHub:**
•	Issues – מערכת תקשורת בין חברי צוות הפיתוח ובין משתמשי המערכת.   **Done**
•	Branches – לכל חבר צוות יש branch. בנוסף לזה יש שני branches: main, develop – ככה שבmain תמיד גרסה עובדת, ובdevelop  עושים את הmerge של כל הbranches  במהלך הפיתוח. - **Done**
•	להשתמש בpull request  לטובת השימוש בbranches. - **Done**
•	Wiki – להוסיף קובץ Instruction למשתמש עבור המערכת. - **Done**

**תרשים מחלקות לבן:**
•	להוריד את המחלקות Role, Guest ו- Subscriber ולהחליף אותם בקשרים עם ה- Trading System. **Done**
•	חסר permission לקשר של owner.  **Done**
•	לחבר בין ה- permission של owner לבין ה- permission של manager – מחלקה או קשר שיחבר ביניהם. **Done**
•	חייב לפחות admin אחד במערכת – להוסיף את זה בקשר admin של user. **Done**
•	היסטוריית הרכישה של user – לחשוב איך כדאי לממש את זה: קשור גם ל- user וגם ל- store **Done**
•	להוסיף מחלקה שהיא Shopping cart שם תתבצע רכישת המוצרים, והיא תהיה מקושרת ל- user ול- External services.
בנוסף, היא תהיה מקושרת גם ל- store וה- Shopping bag יהיה ה- association ביניהם.  **Done**
•	להוריד את הקשר בין ה- Trading System ל- External services. **Done**

**דיאגרמת ארכיטקטורה:**
•	לשנות את הקשרים והמחלקות בהתאם למה ששינינו בתרשים מחלקות לבן  **Done**
•	להוסיף את המחלקה Shopping cart ואת הקשר שלה עם External services. **Done**
•	להוסיף תמיכה האימות סיסמא ושם משתמש, כלומר – בדיקת תקינות. להוסיף מחלקה שתהיה אחראית על זה? **Done**
 
**מילון מונחים:**
•	להוסיף הגדרה ל- user. **Done**
•	הבעייתיות בקונה אורח – מה שיש בתוך הסוגריים לא מוגדר. **Done**

**תוכן עניינים:  להוסיף** **Done**

**תרחישי שימוש:**
_•	תרחיש רכישת מוצרים:_ 
o	במקום המילה 'רכש' להחליף ל- 'בחר'
o	להוריד את המדינויות מתנאי הקדם
o	פרמטרים: במקום פרטי כרטיס אשראי לרשום – פרטי תשלום
o	תהליך: לפצל לתתי תרחישים – הכוונה היא ליצור תרחיש אחד מרכזי שממנו נגזרים עוד כמה תרחישים (שהם חלק ממנו)
o	להוסיף בדיקה האם המוצר במלאי
o	לטפל בהיסטוריית רכישה של מנוי
o	עבור קונה אורח: יש צורף להוסיף בפרמטרים גם הכנסה של פרטי הלקוח: שם, כתובת, טלפון וכו'. לציין שאצל המנוי אין צורך בהכנסת הפרטים האלו מכיוון שהוא רשום למערכת ופרטיו ידועים.
o	מדיניות רכישה ומדיניות הנחה – להפריד ביניהם. המערכת בודקת כל אחד מהם בנפרד.

**Comment by nofetd** [comment]
סיכום פגישה 1 – הערות מנחה

שימוש ב-GitHub:
• Issues – מערכת תקשורת בין חברי צוות הפיתוח ובין משתמשי המערכת. Done
• Branches – לכל חבר צוות יש branch. בנוסף לזה יש שני branches: main, develop – ככה שבmain תמיד גרסה עובדת, ובdevelop עושים את הmerge של כל הbranches במהלך הפיתוח. - Done
• להשתמש בpull request לטובת השימוש בbranches. - Done
• Wiki – להוסיף קובץ Instruction למשתמש עבור המערכת. - Done

תרשים מחלקות לבן:
• להוריד את המחלקות Role, Guest ו- Subscriber ולהחליף אותם בקשרים עם ה- Trading System. Done
• חסר permission לקשר של owner. Done
• לחבר בין ה- permission של owner לבין ה- permission של manager – מחלקה או קשר שיחבר ביניהם. Done
• חייב לפחות admin אחד במערכת – להוסיף את זה בקשר admin של user. Done
• היסטוריית הרכישה של user – לחשוב איך כדאי לממש את זה: קשור גם ל- user וגם ל- store Done
• להוסיף מחלקה שהיא Shopping cart שם תתבצע רכישת המוצרים, והיא תהיה מקושרת ל- user ול- External services.
בנוסף, היא תהיה מקושרת גם ל- store וה- Shopping bag יהיה ה- association ביניהם. Done
• להוריד את הקשר בין ה- Trading System ל- External services. Done

דיאגרמת ארכיטקטורה:
• לשנות את הקשרים והמחלקות בהתאם למה ששינינו בתרשים מחלקות לבן Done
• להוסיף את המחלקה Shopping cart ואת הקשר שלה עם External services. Done
• להוסיף תמיכה האימות סיסמא ושם משתמש, כלומר – בדיקת תקינות. להוסיף מחלקה שתהיה אחראית על זה? Done

מילון מונחים:
• להוסיף הגדרה ל- user. Done
• הבעייתיות בקונה אורח – מה שיש בתוך הסוגריים לא מוגדר. Done

תוכן עניינים: להוסיף Done

תרחישי שימוש:
• תרחיש רכישת מוצרים:
o במקום המילה 'רכש' להחליף ל- 'בחר' **Done**
o להוריד את המדינויות מתנאי הקדם**Done**
o פרמטרים: במקום פרטי כרטיס אשראי לרשום – פרטי תשלום**Done**
o תהליך: לפצל לתתי תרחישים – הכוונה היא ליצור תרחיש אחד מרכזי שממנו נגזרים עוד כמה תרחישים (שהם חלק ממנו)**Done**
o להוסיף בדיקה האם המוצר במלאי**Done**
o לטפל בהיסטוריית רכישה של מנוי**Done**
o עבור קונה אורח: יש צורף להוסיף בפרמטרים גם הכנסה של פרטי הלקוח: שם, כתובת, טלפון וכו'. לציין שאצל המנוי אין צורך בהכנסת הפרטים האלו מכיוון שהוא רשום למערכת ופרטיו ידועים.**Done**
o מדיניות רכישה ומדיניות הנחה – להפריד ביניהם. המערכת בודקת כל אחד מהם בנפרד.**Done**
